// Generated by _src/build.js. Paste this entire file into the Cloudflare Worker editor.
const allowedPages = new Set(["post-jev-output-heads","post-disco-dry-run","post-convmem","post-inverted-fractions","post-glee-agent","post-fair-evaluation","post-student-becomes-teacher","post-optimizing-reasoning","post-race-to-on","post-dendrites-dandelions","post-physical-ai","post-causalpfn","post-geometry-of-forgetting","post-calendering-u-shape"]);

const MAX_BYTES = 32768;
const PAGE_SIZE = 30;
const TOKEN = /^[a-f0-9]{64}$/;
const REQUEST_ID = /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/;
const SELECT = `SELECT c.id, c.page, c.visitor_id AS authorId,
  c.username AS displayName, c.message AS body, c.created_at AS createdAt, c.hidden
  FROM comments c`;
let lastCleanup = 0;

async function digest(value) {
  const hash = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value));
  return [...new Uint8Array(hash)].map(byte => byte.toString(16).padStart(2, '0')).join('');
}
function turnstileSecret(env) { return env.TURNSTILE_SECRET || env.TURNSTILE_SECRET_KEY; }
async function rateLimit(request, env) {
  const minute = Math.floor(Date.now() / 60000);
  const key = request.method + ':' + await digest(turnstileSecret(env) + ':' + (request.headers.get('CF-Connecting-IP') || 'anonymous'));
  const count = await env.DB.prepare(`INSERT INTO rate_limits (key, minute, used) VALUES (?, ?, 1)
    ON CONFLICT(key) DO UPDATE SET used = CASE WHEN minute = excluded.minute THEN used + 1 ELSE 1 END,
    minute = excluded.minute RETURNING used`).bind(key, minute).first();
  if (Date.now() - lastCleanup > 3600000) {
    await env.DB.prepare('DELETE FROM rate_limits WHERE minute < ?').bind(minute - 1440).run();
    lastCleanup = Date.now();
  }
  return count.used <= (request.method === 'POST' ? 5 : 60);
}

async function readBody(request) {
  const reader = request.body?.getReader();
  if (!reader) throw new Error('empty');
  const chunks = []; let length = 0;
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    length += value.byteLength;
    if (length > MAX_BYTES) { await reader.cancel(); throw new Error('large'); }
    chunks.push(value);
  }
  const bytes = new Uint8Array(length); let offset = 0;
  for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; }
  return JSON.parse(new TextDecoder('utf-8', { fatal: true }).decode(bytes));
}
async function authorToken(request) {
  const token = request.headers.get('Authorization')?.match(/^Bearer ([a-f0-9]{64})$/)?.[1];
  if (!token || !TOKEN.test(token)) return null;
  return digest(token);
}
function publicComment(row) {
  return { id: row.id, page: row.page, authorId: row.authorId,
    displayName: row.displayName, body: row.body,
    createdAt: new Date(row.createdAt.endsWith('Z') ? row.createdAt : row.createdAt.replace(' ', 'T') + 'Z').getTime() };
}

export async function handleRequest(request, env, send = fetch) {
  const url = new URL(request.url);
  const allowed = env.SITE_ORIGIN || 'https://j-stoerk.github.io';
  const origin = request.headers.get('Origin');
  const headers = { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store',
    'Vary': 'Origin', 'X-Content-Type-Options': 'nosniff' };
  if (origin === allowed) {
    headers['Access-Control-Allow-Origin'] = allowed;
    headers['Access-Control-Allow-Methods'] = 'GET, POST, OPTIONS';
    headers['Access-Control-Allow-Headers'] = 'Content-Type, Authorization';
  }
  const reply = (status, data) => new Response(JSON.stringify(data), { status, headers });
  const error = (status, message) => reply(status, { ok: false, message });
  if (!['/comments', '/identity'].includes(url.pathname)) return error(404, 'Not found.');
  if ((origin && origin !== allowed) || (request.method === 'POST' && origin !== allowed)) return error(403, 'Use the portfolio to post comments.');
  if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers });
  if (!['GET', 'POST'].includes(request.method) || (url.pathname === '/identity' && request.method !== 'GET')) return error(405, 'Method not allowed.');
  if (!env.DB || !turnstileSecret(env)) return error(503, 'Comments are not connected yet.');

  try {
    if (!await rateLimit(request, env)) return error(429, 'Please wait a minute before trying again.');
    if (url.pathname === '/identity') {
      const hash = await authorToken(request);
      if (!hash) return error(401, 'Choose a valid commenting identity.');
      const identity = await env.DB.prepare('SELECT id, display_name AS displayName, banned FROM identities WHERE token_hash = ?').bind(hash).first();
      if (!identity) return error(401, 'This commenting identity was not found.');
      if (identity.banned) return error(403, 'This identity cannot post comments.');
      return reply(200, { ok: true, identity: { id: identity.id, displayName: identity.displayName } });
    }

    if (request.method === 'GET') {
      const page = url.searchParams.get('page');
      if (!allowedPages.has(page)) return error(400, 'Choose a valid blog post.');
      const rawCursor = url.searchParams.get('cursor');
      if (rawCursor !== null && (!/^[1-9][0-9]{0,15}$/.test(rawCursor) || !Number.isSafeInteger(Number(rawCursor)))) return error(400, 'Invalid comment cursor.');
      const cursor = rawCursor === null ? Number.MAX_SAFE_INTEGER : Number(rawCursor);
      const result = await env.DB.prepare(SELECT + ' WHERE c.page = ? AND c.hidden = 0 AND c.id < ? ORDER BY c.id DESC LIMIT ?')
        .bind(page, cursor, PAGE_SIZE + 1).all();
      if (!result.success || !Array.isArray(result.results)) throw new Error('database');
      const rows = result.results.slice(0, PAGE_SIZE);
      return reply(200, { ok: true, comments: rows.map(publicComment),
        nextCursor: result.results.length > PAGE_SIZE ? rows[rows.length - 1].id : null });
    }

    if (!request.headers.get('Content-Type')?.toLowerCase().startsWith('application/json')) return error(415, 'Send a valid comment.');
    let data;
    try { data = await readBody(request); }
    catch (failure) { return error(failure.message === 'large' ? 413 : 400, 'The comment is invalid or too long.'); }
    if (!data || typeof data !== 'object' || Array.isArray(data)) return error(400, 'Send a valid comment.');
    const name = typeof data.displayName === 'string' ? data.displayName.trim() : '';
    const body = typeof data.body === 'string' ? data.body.trim() : '';
    if (!allowedPages.has(data.page) || !name || name.length > 40 || /[\u0000-\u001f\u007f]/.test(name)
      || !body || body.length > 5000 || /\u0000/.test(body) || typeof data.requestId !== 'string' || !REQUEST_ID.test(data.requestId)
      || typeof data.turnstileToken !== 'string' || !data.turnstileToken || data.turnstileToken.length > 2048
      || data.website !== '') return error(400, 'Please check your name and comment.');
    const hash = await authorToken(request);
    if (!hash) return error(401, 'Choose a valid commenting identity.');
    const authorId = hash.slice(0, 32);
    const identity = await env.DB.prepare('SELECT banned FROM identities WHERE id = ?').bind(authorId).first();
    if (identity?.banned) return error(403, 'This identity cannot post comments.');
    const previous = await env.DB.prepare(SELECT + ' WHERE c.visitor_id = ? AND c.request_id = ?').bind(authorId, data.requestId).first();
    if (previous) {
      if (previous.hidden) return error(410, 'This comment was removed.');
      if (previous.page !== data.page || previous.body !== body) return error(409, 'Please retry with a new comment.');
      return reply(200, { ok: true, comment: publicComment(previous) });
    }

    const verification = await send('https://challenges.cloudflare.com/turnstile/v0/siteverify', {
      method: 'POST', headers: { 'Content-Type': 'application/json' }, signal: AbortSignal.timeout(10000),
      body: JSON.stringify({ secret: turnstileSecret(env), response: data.turnstileToken,
        remoteip: request.headers.get('CF-Connecting-IP') || undefined }),
    });
    if (!verification.ok) return error(503, 'Verification is temporarily unavailable. Your draft is still here.');
    const challenge = await verification.json();
    if (challenge.success !== true || challenge.hostname !== new URL(allowed).hostname || challenge.action !== 'comment') return error(400, 'Verification failed or expired. Please try again.');

    const now = Date.now();
    const results = await env.DB.batch([
      env.DB.prepare('INSERT INTO identities (id, token_hash, display_name, created_at) VALUES (?, ?, ?, ?) ON CONFLICT(id) DO NOTHING').bind(authorId, hash, name, now),
      env.DB.prepare(`INSERT INTO comments (page, visitor_id, username, message, created_at, request_id)
        SELECT ?, id, display_name, ?, ?, ? FROM identities WHERE id = ? AND banned = 0
        ON CONFLICT(visitor_id, request_id) DO NOTHING`).bind(data.page, body, new Date(now).toISOString(), data.requestId, authorId),
    ]);
    if (results.some(result => !result.success)) throw new Error('database');
    const saved = await env.DB.prepare(SELECT + ' WHERE c.visitor_id = ? AND c.request_id = ?').bind(authorId, data.requestId).first();
    if (!saved || saved.hidden) return error(403, 'This comment could not be posted.');
    if (saved.page !== data.page || saved.body !== body) return error(409, 'Please retry with a new comment.');
    return reply(201, { ok: true, comment: publicComment(saved) });
  } catch (_) {
    // No message bodies, IPs, credentials or provider error details are logged.
    return error(503, 'Comments are temporarily unavailable. Your draft is still here.');
  }
}

export default { fetch(request, env) { return handleRequest(request, env); } };
