/* Static site builder for j-stoerk.github.io.
   Zero dependencies. Run: node _src/build.js
   Sources live in _src/pages; shared chrome (head assets, topbar, footer,
   scripts) is injected here so a change lands on every page at once.
   posts.json drives the blog listing, the home-page cards, feed.xml, and
   sitemap.xml, so those can never drift apart again.
   GitHub Pages (Jekyll) ignores underscore directories, so _src is not
   published. */
'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const SRC = __dirname;
const ROOT = path.join(__dirname, '..');
const SITE = 'https://j-stoerk.github.io';

/* Content-hash cache-buster: append ?v=<hash> to a runtime asset so a
   changed file is refetched instead of served stale from browser cache. */
function ver(file) {
  // Normalise line endings before hashing so the cache-buster is identical
  // on Windows (CRLF checkout) and Linux CI (LF), keeping the build
  // deterministic across platforms.
  const text = fs.readFileSync(path.join(ROOT, file), 'utf8').replace(/\r\n/g, '\n');
  return file + '?v=' + crypto.createHash('md5').update(text).digest('hex').slice(0, 8);
}

const posts = JSON.parse(fs.readFileSync(path.join(SRC, 'posts.json'), 'utf8'))
  .sort((a, b) => (a.iso < b.iso ? 1 : -1));
const community = JSON.parse(fs.readFileSync(path.join(SRC, 'community.json'), 'utf8'));
if (community.comments.endpoint && !/^https:\/\/[a-z0-9.-]+(?::\d+)?$/i.test(community.comments.endpoint)) {
  throw new Error('community.json: comments.endpoint must be an HTTPS origin without a trailing slash');
}
fs.mkdirSync(path.join(ROOT, '_services', 'comments'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'comment-pages.json'), JSON.stringify({
  version: 1, pages: posts.map(post => post.file.replace(/\.html$/, '')),
}, null, 2) + '\n');
fs.writeFileSync(path.join(ROOT, '_services', 'comments', 'worker.js'),
  '// Generated by _src/build.js. Paste this entire file into the Cloudflare Worker editor.\n' +
  fs.readFileSync(path.join(ROOT, '_services', 'comments', 'worker.mjs'), 'utf8'));
if (!/^https:\/\/formspree\.io\/f\/[a-z0-9]+$/i.test(community.contact.endpoint)) {
  throw new Error('community.json: contact.endpoint must be a Formspree form URL');
}
function publicConfig(id, value) {
  return `<script type="application/json" id="${id}">${JSON.stringify(value).replace(/</g, '\\u003c')}</script>`;
}
function attribute(value) {
  return String(value).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/* The video, readable tables, and downloads share one audited dataset. */
function batteryMarketData() {
  const data = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/battery-market.json'), 'utf8'));
  const esc = attribute;
  const sourceLink = key => {
    const s = data.sources[key];
    if (!s) throw new Error(`unknown battery-map source ${key}`);
    return `<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>`;
  };
  const csv = [['company', 'year', 'reporting_window', 'months', 'EV_deployment_GWh', 'observed_GWh_per_month', 'source_url']];
  for (const c of data.companies) {
    data.periods.forEach((p, i) => {
      const v = c.volumes[i];
      csv.push([c.name, p.year, p.label, p.months, v ?? '', v === null ? '' : (v / p.months).toFixed(4), v === null ? '' : data.sources[p.source].url]);
    });
  }
  fs.writeFileSync(path.join(ROOT, 'data/battery-market-volumes.csv'), csv.map(row => row.map(value => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\n') + '\n');
  const rows = data.companies.filter(c => c.volumes.some(v => v !== null)).map(c =>
    `<tr><th scope="row">${esc(c.name)}</th>${c.volumes.map(v => `<td>${v === null ? '<span aria-label="Unavailable">—</span>' : v.toFixed(1)}</td>`).join('')}</tr>`).join('\n');
  const events = data.companies.flatMap(c => c.events.filter(e => e.date > '2020-01-01').map(e => ({c, e})))
    .sort((a, b) => a.e.date.localeCompare(b.e.date));
  return `<div class="battery-data-table" role="region" tabindex="0" aria-label="Scrollable deployment data">
  <table><caption>Reported EV battery deployment (GWh). 2020–2025 are complete years; 2026 is January–August only. A dash means unavailable.</caption>
    <thead><tr><th scope="col">Company</th>${data.periods.map(p => `<th scope="col">${p.year}${p.months < 12 ? '<br>Jan–Aug' : ''}</th>`).join('')}</tr></thead>
    <tbody>${rows}</tbody>
  </table></div>
  <div class="prose"><p>Deployment sources by reporting year:</p><ul>${data.periods.map(p => `<li>${p.year} (${p.months} months): ${sourceLink(p.source)}</li>`).join('')}</ul></div>
  <ol class="timeline-milestones">${events.map(({c, e}) => `<li><time datetime="${e.date}">${e.date}</time> · <strong>${esc(c.name)}</strong> — ${esc(e.text)} ${sourceLink(e.source)}${e.capacitySource ? '; capacity: ' + sourceLink(e.capacitySource) : ''}.</li>`).join('\n')}</ol>`;
}

/* ---------- page configuration ---------- */
const PAGES = {
  'index.html': {
    nav: null, home: true, extraScripts: ['cite.js', 'experiences.js', 'bio-popovers.js', 'comment-identity.js', 'contact.js'],
    footerExtra: null, lastmod: '2026-10-07', priority: '1.0',
  },
  'cv.html': {
    nav: 'cv', extraScripts: [],
    footerExtra: '<a href="index.html">Home</a> · <a href="cv.pdf" download>CV (PDF)</a>',
    lastmod: '2026-10-01', priority: '0.8',
  },
  'blog.html': {
    nav: 'blog', extraScripts: ['blog-view.js'],
    footerExtra: '<a href="index.html">Home</a> · <a href="index.html#contact">Contact</a>',
    lastmod: '2026-10-07', priority: '0.8',
  },
  /* Served by GitHub Pages for any missing URL; noindex, not in sitemap. */
  '404.html': {
    nav: null, extraScripts: [],
    footerExtra: '<a href="index.html">Home</a> · <a href="index.html#contact">Contact</a>',
    lastmod: null, priority: null,
  },
};
for (const p of posts) {
  PAGES[p.file] = {
    nav: 'blog', extraScripts: ['blog.js', 'comment-identity.js', 'comments.js', ...(p.scripts || [])],
    extraStyles: p.styles || [],
    footerExtra: '<a href="blog.html">All posts</a>',
    lastmod: p.lastmod, priority: '0.7', math: !!p.math,
  };
}

/* ---------- build-time math (KaTeX) ----------
   $$...$$ (display) and \( ... \) (inline) in a math-flagged page source
   are rendered to static HTML+MathML here; the browser only needs
   katex/katex.min.css and its fonts, no client-side JS. */
let katex = null;
function renderMath(html, file) {
  if (!katex) katex = require('./vendor/katex.min.js');
  const opts = { output: 'htmlAndMathml', throwOnError: true };
  html = html.replace(/\$\$([\s\S]+?)\$\$/g, (m, tex) =>
    katex.renderToString(tex.trim(), { ...opts, displayMode: true }));
  html = html.replace(/\\\((.+?)\\\)/g, (m, tex) =>
    katex.renderToString(tex.trim(), { ...opts, displayMode: false }));
  return html;
}

/* ---------- shared chrome ---------- */
const HEAD_ASSETS = `  <meta name="theme-color" content="#fdfdfc">
  <link rel="apple-touch-icon" href="apple-touch-icon.png">

  <!-- Applied before first paint so the theme never flashes. -->
  <script>
    (function () {
      var t;
      try { t = localStorage.getItem('theme'); } catch (e) { }
      if (!t) t = 'light';   // light is the standard; dark only on explicit toggle
      document.documentElement.setAttribute('data-theme', t);
      var m = document.querySelector('meta[name="theme-color"]');
      if (m) m.setAttribute('content', t === 'dark' ? '#101214' : '#fdfdfc');
    })();
  </script>

  <link rel="preload" href="fonts/noto-sans-latin-wght.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="${ver('styles.css')}">
  <link rel="stylesheet" href="${ver('experiences.css')}">`;

const NAV_ITEMS = [
  ['publications', 'Publications', '#publications'],
  ['software', 'Code', '#software'],
  ['blog', 'Blog', 'blog.html'],
  ['experience', 'Experience', '#experience'],
  ['cv', 'CV', 'cv.html'],
  ['contact', 'Contact', '#contact'],
];
// Refresh cached documents whenever the shared navigation changes.
const NAV_VERSION = crypto.createHash('md5').update(JSON.stringify(NAV_ITEMS)).digest('hex').slice(0, 8);

function topbar(cfg) {
  const links = NAV_ITEMS.map(([key, label, href]) => {
    const url = href.startsWith('#') && !cfg.home ? 'index.html' + href : href;
    const cur = key === cfg.nav ? ' class="current"' : '';
    const aria = key === cfg.nav ? ' aria-current="page"' : '';
    return `        <a${cur} href="${url}" data-nav-label="${label}"${aria}>${label}</a>`;
  }).join('\n');
  const title = cfg.home
    ? '<a class="site-title" href="#home" aria-current="page">Home</a>'
    : '<a class="site-title" href="index.html">Home</a>';
  return `  <header class="topbar">
    <div class="topbar-inner">
      ${title}
      <button class="nav-toggle" type="button" data-nav-toggle aria-controls="primary-nav" aria-expanded="false">
        <span class="nav-toggle-lines" aria-hidden="true"></span>
        <span class="sr-only">Open navigation</span>
      </button>
      <nav class="nav" id="primary-nav" data-nav aria-label="Primary">
${links}
        <button class="theme-toggle" type="button" data-theme-toggle aria-label="Switch theme">◐</button>
      </nav>
    </div>
  </header>`;
}

function footer(cfg) {
  const extra = cfg.footerExtra ? `\n    <span>${cfg.footerExtra}</span>` : '';
  return `  <footer class="content">
    <span>© 2026 Julius Störk</span>${extra}
  </footer>`;
}

function scripts(cfg) {
  const extras = cfg.extraScripts.filter(s => !(cfg.home && s === 'experiences.js'))
    .map((s) => `  <script defer src="${ver(s)}"></script>`).join('\n');
  /* GoatCounter is injected after window load so a slow or filtered
     analytics host can never hold the page in its loading state
     (busy cursor / tab spinner). */
  return `  <script defer src="${ver('theme.js')}"></script>
  <script defer src="${ver('navigation.js')}"></script>
  <script defer src="${ver('media.js')}"></script>
  <script defer src="${ver('interactions.js')}"></script>
  <script defer src="${ver('portal-transitions.js')}"></script>
${extras ? extras + '\n' : ''}  <script>
    window.addEventListener('load', function () {
      var s = document.createElement('script');
      s.async = true;
      s.src = 'https://gc.zgo.at/count.js';
      s.setAttribute('data-goatcounter', 'https://jstoerk.goatcounter.com/count');
      document.body.appendChild(s);
    });
  </script>`;
}

/* ---------- post listings ---------- */
/* Reuse the actual post artwork for tiles. External SVGs isolate each cover's
   gradient IDs and keep the index small; generated assets are committed too. */
function postCover(p) {
  const source = fs.readFileSync(path.join(SRC, 'pages', p.file), 'utf8');
  const cover = source.match(/<svg\b[^>]*class="cover-art"[\s\S]*?<\/svg>/);
  if (!cover) throw new Error(`${p.file}: missing cover artwork for blog tiles`);
  const target = `images/blog-covers/${p.file.replace(/\.html$/, '.svg')}`;
  fs.mkdirSync(path.dirname(path.join(ROOT, target)), { recursive: true });
  const svg = cover[0].replace('<svg', '<svg xmlns="http://www.w3.org/2000/svg"');
  fs.writeFileSync(path.join(ROOT, target), svg + '\n');
  return ver(target);
}

/* CSS repeats each article's bespoke line art without stretching it. Export
   both themes from the shared ink rules so no runtime SVG cloning is needed. */
const siteStyles = fs.readFileSync(path.join(ROOT, 'styles.css'), 'utf8').replace(/\r\n/g, '\n');
const inkStart = siteStyles.indexOf('.art-ink,\n');
const inkEnd = siteStyles.indexOf('\nbody::before', inkStart);
if (inkStart < 0 || inkEnd < 0) throw new Error('missing shared line-art styles');
const inkStyles = siteStyles.slice(inkStart, inkEnd).trim();
const artThemes = {
  light: siteStyles.match(/:root,\s*\[data-theme="light"\]\s*\{([\s\S]*?)\n\}/)[1],
  dark: siteStyles.match(/\[data-theme="dark"\]\s*\{([\s\S]*?)\n\}/)[1],
};
function postBackground(html, file) {
  const marker = '<!--#POST_BACKGROUND-->';
  if (!html.includes(marker)) throw new Error(`${file}: missing article background marker`);
  const artwork = fs.readFileSync(path.join(SRC, 'blog-art', file.replace(/\.html$/, '.svg')), 'utf8').trimEnd();
  if (!/<svg\b[^>]*width="\d+"[^>]*height="\d+"/.test(artwork)) {
    throw new Error(`${file}: background needs explicit tile dimensions`);
  }
  const assets = Object.entries(artThemes).map(([theme, tokens]) => {
    const styles = inkStyles.replace(/var\((--art-ink(?:-soft)?)\)/g,
      (_, token) => tokens.match(new RegExp(`${token}:\\s*([^;]+);`))[1]);
    const svg = artwork.replace(/(<svg\b[^>]*>)/, (_, tag) => `${tag}<style>${styles}</style>`);
    const target = `images/blog-backgrounds/${file.replace(/\.html$/, '')}-${theme}.svg`;
    fs.mkdirSync(path.dirname(path.join(ROOT, target)), { recursive: true });
    fs.writeFileSync(path.join(ROOT, target), svg + '\n');
    return `--post-art-${theme}:url('${ver(target)}')`;
  });
  return html.replace(marker, () => `<div class="page-art page-art-post" aria-hidden="true" style="${assets.join(';')}"></div>`);
}

function postEntry(p, withMinutes, indent) {
  const meta = withMinutes ? `${p.category} · ${p.minutes} min` : p.category;
  const pad = ' '.repeat(indent);
  return `${pad}<article class="journal-entry">
${withMinutes ? `${pad}  <div class="journal-thumbnail"><img src="${postCover(p)}" alt="" width="1200" height="675" loading="lazy" decoding="async"></div>\n` : ''}${pad}  <div class="journal-meta"><time datetime="${p.iso}">${p.display}</time><span>${meta}</span></div>
${pad}  <div class="journal-copy"><h3><a class="card-link" href="${p.file}">${p.title}</a></h3><p>${p.summary}</p></div>
${pad}  <span class="journal-arrow" aria-hidden="true">↗</span>
${pad}</article>`;
}

const POST_LIST = `<div id="blog-posts" class="journal-index journal-index-page" data-blog-view="tiles">
${posts.map((p) => postEntry(p, true, 6)).join('\n')}
    </div>`;

function trailStory(p, preview = true) {
  return `<a class="atlas-story" data-post="${p.file}" data-preview="${preview}"${preview ? '' : ' hidden'} href="${p.file}"><img src="${postCover(p)}" alt="" width="1200" height="675" loading="lazy"><span class="atlas-story-copy"><small>${p.display} &middot; ${p.category}</small><strong>${p.title}</strong><span class="atlas-intro">${p.summary}</span><em>Read the notes &#8599;</em></span></a>`;
}
const BLOG_LATEST = posts.slice(0, 2).map(p => trailStory(p)).join('\n              ');
const TRAILS = { materials: 'Materials', learning: 'Learning', modelling: 'Modelling', automation: 'Automation' };
for (const p of posts) {
  if (!TRAILS[p.trail]) throw new Error(`${p.file}: missing or invalid blog trail`);
}
const BLOG_TRAILS = Object.entries(TRAILS).map(([trail, label]) =>
  `<div class="atlas-panel" id="atlas-${trail}" role="region" aria-label="${label} blog posts">\n              ${posts.filter(p => p.trail === trail).map((p, i) => trailStory(p, i < 2)).join('\n              ')}\n            </div>`
).join('\n            ');

/* ---------- build pages ---------- */
const pagesDir = path.join(SRC, 'pages');
for (const file of fs.readdirSync(pagesDir)) {
  if (!file.endsWith('.html')) continue;
  const cfg = PAGES[file];
  if (!cfg) throw new Error(`no page config for ${file}`);
  let html = fs.readFileSync(path.join(pagesDir, file), 'utf8');
  if (html.includes('<!--#BATTERY_MARKET_DATA-->')) html = html.replace('<!--#BATTERY_MARKET_DATA-->', batteryMarketData);
  let headAssets = cfg.math
    ? HEAD_ASSETS + '\n  <link rel="stylesheet" href="katex/katex.min.css">'
    : HEAD_ASSETS;
  headAssets += (cfg.extraStyles || []).map(s => `\n  <link rel="stylesheet" href="${ver(s)}">`).join('');
  if (cfg.home) headAssets += `\n  <script defer fetchpriority="high" src="${ver('experiences.js')}"></script>`;
  html = html
    .replace('  <!--#HEAD_ASSETS-->', headAssets)
    .replace('  <!--#TOPBAR-->', topbar(cfg))
    .replace('  <!--#FOOTER-->', footer(cfg))
    .replace('  <!--#SCRIPTS-->', scripts(cfg))
    .replace('<!--#POST_LIST-->', POST_LIST);
  html = html.replace('<!--#BIO_POPOVERS-->', () => fs.readFileSync(path.join(SRC, 'bio-popovers.html'), 'utf8'));
  html = html.replace('<!--#RESEARCH_ATLAS-->', () => fs.readFileSync(path.join(SRC, 'research-atlas.html'), 'utf8'));
  html = html.replace('<!--#BLOG_LATEST-->', () => BLOG_LATEST);
  html = html.replace('<!--#BLOG_TRAILS-->', () => BLOG_TRAILS);
  html = html.replace('<!--#CONTACT_FORM-->', () => fs.readFileSync(path.join(SRC, 'contact-form.html'), 'utf8')
    .replace('<!--#CONTACT_ENDPOINT-->', () => community.contact.endpoint)
    .replace('<!--#COMMENT_SERVICE-->', () => attribute(community.comments.endpoint)));
  if (cfg.nav === 'blog' && file !== 'blog.html') {
    const post = posts.find(p => p.file === file);
    if (!post?.whyItMatters) throw new Error(`${file}: missing whyItMatters`);
    const context = post.whyItMatters.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    html = html.replace('<!--#POST_CONTEXT-->', `<p class="post-context"><span>Why this matters</span>${context}</p>`);
    html = postBackground(html, file);
    const comments = community.comments.endpoint && community.comments.turnstileSiteKey ? fs.readFileSync(path.join(SRC, 'comments.html'), 'utf8')
      .replace('<!--#COMMENTS_CONFIG-->', () => publicConfig('comments-config', {
        endpoint: community.comments.endpoint,
        turnstileSiteKey: community.comments.turnstileSiteKey,
        sectionId: file.replace(/\.html$/, ''),
      })) : '';
    if (!html.includes('    <nav class="post-pager"')) throw new Error(`${file}: missing post pager`);
    if (comments) html = html.replace('    <nav class="post-pager"', () => comments + '\n\n    <nav class="post-pager"');
  }
  if (cfg.math) html = renderMath(html, file);
  html = html.replace(/href="([^":?#]+\.html)(#[^"]*)?"/g,
    (_, page, hash = '') => `href="${page}?nav=${NAV_VERSION}${hash}"`);
  if (/<!--#/.test(html)) throw new Error(`${file}: unresolved marker`);
  fs.writeFileSync(path.join(ROOT, file), html);
  console.log('built', file);
}

/* ---------- feed.xml ---------- */
const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const feedItems = posts.map((p) => `    <item>
      <title>${esc(p.title)}</title>
      <link>${SITE}/${p.file}</link>
      <guid isPermaLink="true">${SITE}/${p.file}</guid>
      <pubDate>${p.rfc822}</pubDate>
      <description>${esc(p.feedDescription)}</description>
    </item>`).join('\n');
fs.writeFileSync(path.join(ROOT, 'feed.xml'), `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Research notes · Julius Störk</title>
    <link>${SITE}/blog.html</link>
    <description>Interactive notes on continual learning and electrode manufacturing.</description>
    <language>en</language>
    <atom:link href="${SITE}/feed.xml" rel="self" type="application/rss+xml" />
${feedItems}
  </channel>
</rss>
`);
console.log('built feed.xml');

/* ---------- sitemap.xml ---------- */
const order = ['index.html', 'cv.html', 'blog.html', ...posts.map((p) => p.file)];
const urls = order.map((f) => {
  const cfg = PAGES[f];
  const loc = f === 'index.html' ? `${SITE}/` : `${SITE}/${f}`;
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${cfg.lastmod}</lastmod>
    <priority>${cfg.priority}</priority>
  </url>`;
}).join('\n');
fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`);
console.log('built sitemap.xml');

/* ---------- publications.bib ----------
   Extracted from the BibTeX blocks in the built index page, so the
   download can never drift from what the site shows. */
const indexHtml = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const bibEntries = [...indexHtml.matchAll(/<pre><code>(@[\s\S]*?)<\/code><\/pre>/g)]
  .map((m) => m[1].trim());
if (bibEntries.length === 0) throw new Error('no BibTeX entries found in index.html');
fs.writeFileSync(path.join(ROOT, 'publications.bib'),
  `% Publications · Julius Störk · https://j-stoerk.github.io/
% Generated by _src/build.js; do not edit by hand.

${bibEntries.join('\n\n')}
`);
console.log(`built publications.bib (${bibEntries.length} entries)`);
